version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    # environment:
    #   DATABASE_HOST: database
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: 
    #   POSTGRES_DB: crj_cms_dev
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: redis

  database:
    image: postgres
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: CHANGE_ME
    #   POSTGRES_DB: CHANGE_ME
    env_file:
      - .env/development/database
