version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
      - .env.docker
    depends_on:
      - database
    networks:
      - default

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env
      - .env.docker
  #   volumes:
  #   - db_data:/var/lib/postgresql/data
  #
  # volumes:
  #   db_data:
